services:


  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vacations_db
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend-flask/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql:ro
    networks:
      - app_network


  backend:
    build: ./backend-flask
    container_name: vacations_backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=vacations_db
      - MYSQL_USER=root
      - MYSQL_HOST=mysql
    volumes:
      - ./backend-flask/uploads/VacationsImages:/app/uploads/VacationsImages
    depends_on:
      - mysql
    networks:
      - app_network
    command: ["python", "app.py"]

  frontend:
    build: ./my-react-app
    container_name: react_app
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app_network
    environment:
      - VITE_API_URL=http://localhost:5000

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:

